// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START set_custom_object_modular]
import { doc, setDoc } from "firebase/firestore"; 

class Plato {
    constructor (id, categoria, descripcion, precio, url ) {
        this.id = id;
        this.categoria = categoria;
        this.descripcion = descripcion;
        this.precio = precio;
        this.url = url;
    }
    toString() {
        return this.id + ', ' +  this.categoria + ', ' +  this.descripcion + ', ' + this.precio + ', ' + this.url;
    }
}
//npm run snippets

// Firestore data converter
const platoConverter = {
    toFirestore: (plato) => {
        return {
            id: plato.id,
            categoria: plato.categoria,
            descripcion: plato.descripcion,
            precio: plato.precio,
            url: plato.url,
            };
    },
    fromFirestore: (snapshot, options) => {
        const data = snapshot.data(options);
        return new Plato(data.id, data.categoria, data.descripcion, data.precio, data.url);
    }
};


const ref = doc(db, "Platos", "1").withConverter(platoConverter);
await setDoc(ref, new Plato(e.id, e.categoria, e.descripcion,e.precio, e.rul));

// leer y actualizar
/*
import { doc, setDoc } from "firebase/firestore";
const PlatosRef = doc(db, 'Platos', 'BJ');
setDoc(PlatosRef, { capital: true }, { merge: true });
*/
// Node.js uses JavaScript objects
//await db.collection('Platos').doc('new-city-id').set(data);